<?php

// This file was generated by running "composer dump-env prod"

return array (
  'APP_ENV' => 'prod',
  'OKTA_CLIENT_ID' => '0oag4cjleQ4p33YBk5d6',
  'OKTA_CLIENT_SECRET' => 'QoLYrLbCTO_2An_j-oylGI19pj58I7C375TxwYMt',
  'OKTA_AUDIENCE' => 'api://default',
  'OKTA_ISSUER' => 'https://dev-21853914.okta.com/oauth2/default',
  'OKTA_SCOPE' => 'customer_api',
  'OKTA_SERVICE_APP_ID' => '0oag4bm59nrWycjAo5d6',
  'OKTA_SERVICE_APP_SECRET' => 'yKZsMza9JfMVpcwlaRmjnexSohUKgzLiofgnUT1-',
);
